sources:
  - name: Farms
    handler:
      openapi:
        baseUrl: https://run.mocky.io/v3/af5d42dc-0769-43ac-9713-624238468cb8
        source: ./farms-api-definition.json
  - name: Exchange
    handler:
      graphql:
        endpoint: https://{context.subgraphHost:api.thegraph.com/subgraphs/name}/{context.subgraphName:sushiswap/sushiswap-avalanche}
  # - name: Staking
  #   handler:
  #     graphql:
  #       endpoint: https://{context.subgraphHost:api.thegraph.com/subgraphs/name}/{context.subgraphName:olastenberg/staking-arbitrum}
  - name: Bar
    handler:
      graphql:
        endpoint: https://{context.subgraphHost:api.thegraph.com/subgraphs/name}/{context.subgraphName:matthewlilley/bar}
  - name: Blocks-ethereum
    handler:
      graphql:
        endpoint: https://{context.subgraphHost:api.thegraph.com/subgraphs/name}/{context.subgraphName:blocklytics/ethereum-blocks}
  - name: Trident
    handler:
      graphql:
        endpoint: https://{context.subgraphHost:api.thegraph.com/subgraphs/name}/{context.subgraphName:sushiswap/trident-optimism}


additionalTypeDefs: |
  extend type Pair {
    volume7d: BigDecimal!
    chainId: BigInt!
    chainName: String!
    chainShortName: String!
  }
  extend type Bundle {
    chainId: BigInt!
    chainName: String!
  }
  extend type User {
    chainId: BigInt!
    chainName: String!
  }
  extend type Query {
    crossChainPair(id: String!, now: Int!, chainId: BigInt!): Pair!
    crossChainPairs(
      first: Int!,
      skip: Int! = 0, 
      where: Pair_filter, 
      orderBy: Pair_orderBy, 
      orderDirection: OrderDirection, 
      chainIds: [BigInt!]!, 
      now: Int!
    ): [Pair!]!
    crossChainBundles(first: Int!, chainIds: [BigInt!]!): [Bundle!]!
    crossChainUser(id: String!, chainIds: [BigInt!]!, now: Int!): User!
  }

additionalResolvers:
  - ./resolvers.ts

documents:
  - ./query.graphql

codegen:
  contextType: 'MeshContext & { chainId: string; chainName: string; chainShortName: string; subgraphName: string; subgraphHost: string }'
